apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
- gateway.yaml
- namespace.yaml

patches:
- patch: |-
    apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: todo-backend-backup
    $patch: delete
  target:
    kind: CronJob
    name: todo-backend-backup
images:
- name: joelheusala/broadcaster
  newName: europe-north1-docker.pkg.dev/project-2fd7f60b-69b9-4e19-b97/my-repository/broadcaster
  newTag: 90ee3b168c2048abf871b97cce2935c9fef8a4cd
- name: joelheusala/todo-app
  newName: europe-north1-docker.pkg.dev/project-2fd7f60b-69b9-4e19-b97/my-repository/todo-app
  newTag: 90ee3b168c2048abf871b97cce2935c9fef8a4cd
- name: joelheusala/todo-backend
  newName: europe-north1-docker.pkg.dev/project-2fd7f60b-69b9-4e19-b97/my-repository/todo-backend
  newTag: 90ee3b168c2048abf871b97cce2935c9fef8a4cd
- name: joelheusala/wikipedia-reader
  newName: europe-north1-docker.pkg.dev/project-2fd7f60b-69b9-4e19-b97/my-repository/wikipedia-reader
  newTag: 90ee3b168c2048abf871b97cce2935c9fef8a4cd
