apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- gateway.yaml
- route.yaml

images:
- name: joelheusala/todo-app
  newName: europe-north1-docker.pkg.dev/project-2fd7f60b-69b9-4e19-b97/my-repository/todo-app
  newTag: e773a1175f685ba02457fda32baaf5199a1efe9c
- name: joelheusala/todo-backend
  newName: europe-north1-docker.pkg.dev/project-2fd7f60b-69b9-4e19-b97/my-repository/todo-backend
  newTag: e773a1175f685ba02457fda32baaf5199a1efe9c
- name: joelheusala/wikipedia-reader
  newName: europe-north1-docker.pkg.dev/project-2fd7f60b-69b9-4e19-b97/my-repository/wikipedia-reader
  newTag: e773a1175f685ba02457fda32baaf5199a1efe9c
