apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - gateway.yaml
  - route.yaml

images:
  - name: joelheusala/todo-app
    newTag: "3.5"
  - name: joelheusala/todo-backend
    newTag: "3.5"
