apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v1
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v1
  template:
    metadata:
      labels:
        app: greeter
        version: v1
    spec:
      containers:
        - name: greeter
          image: joelheusala/greeter:1.0
          ports:
            - containerPort: 8080
          env:
            - name: GREETING
              value: "Hello from version 1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v2
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v2
  template:
    metadata:
      labels:
        app: greeter
        version: v2
    spec:
      containers:
        - name: greeter
          image: joelheusala/greeter:1.0
          ports:
            - containerPort: 8080
          env:
            - name: GREETING
              value: "Hello from version 2"
