apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
          - name: generator
            image: joelheusala/log-output-generator:1.10
            volumeMounts:
              - name: shared-image
                mountPath: /shared
          - name: reader
            image: joelheusala/log-output-reader:1.11
            env:
              - name: PORT
                value: "8080"
            volumeMounts:
              - name: shared-image
                mountPath: /shared
     
