name: Release application

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  id-token: write

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repository
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-update:
    name: Build, Publish and Update GitOps
    runs-on: ubuntu-latest
    environment: GKE_PROJECT

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v3

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker $REGISTRY

      - name: Form image tags
        run: |
          echo "TODO_APP_IMAGE=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-app:$GITHUB_SHA" >> $GITHUB_ENV
          echo "TODO_BACKEND_IMAGE=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:$GITHUB_SHA" >> $GITHUB_ENV
          echo "WIKIPEDIA_READER_IMAGE=$REGISTRY/$PROJECT_ID/$REPOSITORY/wikipedia-reader:$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and publish todo-app
        run: |
          docker build --tag "$TODO_APP_IMAGE" ./todo-app
          docker push "$TODO_APP_IMAGE"

      - name: Build todo-backend
        run: docker build --tag $TODO_BACKEND_IMAGE ./todo-backend

      - name: Build wikipedia-reader
        run: docker build --tag $WIKIPEDIA_READER_IMAGE ./wikipedia-reader

      - name: Publish todo-backend
        run: docker push $TODO_BACKEND_IMAGE

      - name: Publish wikipedia-reader
        run: docker push $WIKIPEDIA_READER_IMAGE

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Update image tags in Kustomize
        working-directory: project/overlays/gke
        run: |
          kustomize edit set image joelheusala/todo-app=$TODO_APP_IMAGE
          kustomize edit set image joelheusala/todo-backend=$TODO_BACKEND_IMAGE
          kustomize edit set image joelheusala/wikipedia-reader=$WIKIPEDIA_READER_IMAGE

      - name: Commit updated kustomization.yaml
        uses: EndBug/add-and-commit@v10
        with:
          add: 'project/overlays/gke/kustomization.yaml'
          message: "New application version released ${{ github.sha }}"
